branch-defaults:
  device_module:
    environment: flask-env
environment-defaults:
  flask-env:
    branch: null
    repository: null
global:
  application_name: flask-tutorial
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
